services:
  db:
    image: postgres:12.22-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  pgadmin:
    image: elestio/pgadmin:REL-8_13
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
volumes:
  postgresql:
  postgresql_data: